import json
import re
import pandas as pd

# The input data
INPUT_JSON = "data/test_data/data_with_queries.jsonl"
OUTPUT_JSON = "data/test_data/rag_ready_w_queries.jsonl"

def process_entry(line):
    obj = json.loads(line)
    
    # data generated by gemini contained [cite: 123], which influenced the testing
    cite_pattern = r'\[cite:[^\]]*\]'
    cleaned_queries = [re.sub(cite_pattern, "", q).strip() for q in obj["queries"]]
    
    # connect the first 6 arguments
    keys_to_join = ["name", "aliases", "short description", "typical applications", "tags"]
    
    # Constructing "key: value [SEP] key: value..."
    details_parts = []
    for key in keys_to_join:
        value = obj.get(key, "")
        details_parts.append(f"{key}: {value}")
    
    equipment_details = " [SEP] ".join(details_parts)
    
    # Create the new dictionary structure
    transformed_data = {
        "equipment_description": equipment_details,
        "queries": cleaned_queries
    }
    
    return transformed_data

with open(INPUT_JSON, "r") as fin, open(OUTPUT_JSON, "w") as fout:
    for line in fin:
        processed_line = process_entry(line)
        print(processed_line)
        fout.write(json.dumps(processed_line) + '\n')
